/* Nova Crest clone style: internal pages keep the same cream canvas, bold rounded type, coral actions, lilac highlights, and shared school shell. */
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, CheckCircle2, Mail, MapPin, Phone } from "lucide-react";

const logo = "https://novacrestacademy.netlify.app/assets/School%20Logo.jpeg";
const pageData = {
  admissions: { kicker: "Admissions", title: "Give your learner a bright place to begin.", intro: "Applications are now open for the July 2026 intake. We welcome curious young minds ages 3 to 4 into a safe, creative, and forward-looking school community.", points: ["A caring, play-based early learning environment", "Small classes with qualified, attentive teachers", "A smooth transition from kindergarten into primary school"] },
  hostel: { kicker: "Hostel Services", title: "A second home for growing minds.", intro: "Our hostel support is designed around safety, routine, and a sense of belonging so learners can focus on friendship, learning, and healthy independence.", points: ["Structured routines and caring supervision", "Comfortable spaces for rest, study, and play", "A supportive community that feels like family"] },
  gallery: { kicker: "Learner Gallery", title: "A school day full of colour and possibility.", intro: "From creative arts to classroom discovery, explore the moments that make Nova Crest Academy a vibrant place to learn.", points: ["Creative arts and practical learning", "Collaborative classroom activities", "Sports, play, and everyday discovery"] },
  fees: { kicker: "Fees & Payments", title: "Clear, simple steps for your school journey.", intro: "Our fee structure is designed to make planning easy for families. Contact the school office for the latest enrollment and payment guidance.", points: ["Kindergarten — N$450/mo", "Pre-Primary — N$550/mo", "Grade 1 to Grade 3 — N$650/mo"] },
} as const;

type PageType = keyof typeof pageData;

function MiniHeader() { return <><div className="bg-[#0b5b4d] py-2 text-center text-[11px] text-white">📍 Onanda Junction, Ogongo Circuit <span className="mx-2">|</span> 📞 081 800 8007</div><header className="border-b border-[#f0e4da] bg-white"><div className="shell flex h-[76px] items-center justify-between"><Link href="/" className="flex items-center gap-3"><img src={logo} alt="Nova Crest" className="h-12 w-12 rounded-full object-cover"/><span className="display text-2xl">Nova Crest</span></Link><nav className="hidden items-center gap-5 text-sm font-bold md:flex"><Link href="/">Home</Link><Link href="/admissions">Admissions</Link><Link href="/hostel">Hostel</Link><Link href="/gallery">Gallery</Link><Link href="/fees">Fees</Link><Link href="/admissions" className="pill bg-[#f58a67] px-5 py-3 text-xs font-bold text-white">CONTACT US</Link></nav><Link href="/admissions" className="pill bg-[#f58a67] px-5 py-3 text-xs font-bold text-white md:hidden">CONTACT US</Link></div></header></> }

export default function InnerPage({ type }: { type: PageType }) { const data = pageData[type]; const editable = trpc.content.get.useQuery({ contentKey: `${type}.hero` }); const displayData = { ...data, kicker: editable.data?.title || data.kicker, title: editable.data?.title || data.title, intro: editable.data?.body || data.intro }; return <div className="min-h-screen bg-[#fffaf5]"><MiniHeader/><main><section className="shell grid items-center gap-10 py-20 md:grid-cols-[1.05fr_.95fr] md:py-28"><div><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#f58a67]"><ArrowLeft size={16}/> Back home</Link><div className="eyebrow mt-10">{displayData.kicker}</div><h1 className="display mt-4 max-w-2xl text-5xl leading-[.98] text-[#17263a] sm:text-7xl">{displayData.title}</h1><p className="mt-7 max-w-xl text-base leading-8 text-[#657080]">{displayData.intro}</p><Link href="/admissions" className="pill mt-8 inline-flex items-center gap-2 bg-[#f58a67] px-7 py-4 text-sm font-bold text-white">Talk to the school <ArrowRight size={17}/></Link></div><div className="soft-card relative overflow-hidden bg-[#fff1e9] p-8 md:p-12"><div className="absolute -right-8 -top-10 text-[130px] opacity-20">{type === "fees" ? "📚" : type === "gallery" ? "🎨" : type === "hostel" ? "🏡" : "🌱"}</div><div className="relative"><div className="display text-3xl text-[#17263a]">Nova Crest Academy</div><p className="mt-2 text-sm leading-6 text-[#697584]">Embrace • Elevate • Excel</p><div className="mt-8 grid gap-4">{data.points.map((point) => <div key={point} className="flex gap-3 rounded-2xl bg-white p-4 text-sm leading-6 text-[#526070]"><CheckCircle2 className="mt-1 shrink-0 text-[#b86be7]" size={18}/>{point}</div>)}</div></div></div></section><section className="bg-[#eaf4ee] py-16"><div className="shell grid gap-7 md:grid-cols-3"><div><MapPin className="text-[#f58a67]"/><h2 className="display mt-3 text-2xl">Find us</h2><p className="mt-2 text-sm leading-6 text-[#697584]">Onanda Junction, Ogongo Circuit<br/>P O Box 531, Okahao</p></div><div><Phone className="text-[#f58a67]"/><h2 className="display mt-3 text-2xl">Call us</h2><p className="mt-2 text-sm leading-6 text-[#697584]">081 800 8007<br/>Our team is ready to help.</p></div><div><Mail className="text-[#f58a67]"/><h2 className="display mt-3 text-2xl">Email us</h2><p className="mt-2 text-sm leading-6 text-[#697584]">novacrestprivateschool@gmail.com</p></div></div></section></main><footer className="bg-[#17263a] py-6 text-center text-xs text-white/50">© 2024 Nova Crest Academy Private School. All rights reserved.</footer></div> }
