document.getElementById('login-form').addEventListener('submit', event => { event.preventDefault(); document.getElementById('login-screen').classList.add('is-hidden'); document.querySelector('.app-shell').classList.remove('is-hidden'); }); document.getElementById('open-web-admin').addEventListener('click', () => window.novaCrestDesktop?.openWebAdmin?.());

const views = {
  overview: { title: 'Good morning, Administrator', render: overview },
  learners: { title: 'Learners & Classes', render: () => tableView('Learners & Classes', 'Manage learner records and class assignments', ['Learner', 'Class', 'Parent link', 'Status'], [['No learner data loaded yet', '—', '—', 'Connect Supabase to load records', '']]) },
  parents: { title: 'Parent Accounts', render: () => tableView('Parent Accounts', 'Issue, reset, and suspend parent access', ['Parent', 'Username', 'Children', 'Status'], [['No parent accounts loaded yet', '—', '—', 'Awaiting connection', '']]) },
  performance: { title: 'Performance', render: () => tableView('Performance', 'Review learner marks and export summaries', ['Learner', 'Activity', 'Marks', 'Percentage'], [['No performance entries loaded yet', '—', '—', '—']]) },
  attendance: { title: 'Attendance', render: () => formView('Attendance register', 'Record daily attendance and review learner history', ['Learner name', 'Date', 'Status', 'Note']) },
  updates: { title: 'Urgent Updates', render: () => formView('Publish an urgent update', 'Communicate time-sensitive notices to parents', ['Title', 'Message', 'Expiry date', 'Visible to parents']) },
  documents: { title: 'Class-list Files', render: () => uploadView() },
  content: { title: 'Site Content', render: () => formView('Edit public content', 'Update the copy shown across the Nova Crest website', ['Content key', 'Title', 'Body', 'Image URL']) }
};

const view = document.getElementById('view');
document.getElementById('current-date').textContent = new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date());
document.querySelectorAll('.nav-item').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.nav-item').forEach(item => item.classList.remove('active')); button.classList.add('active'); const entry = views[button.dataset.view]; document.getElementById('page-title').textContent = entry.title; view.innerHTML = entry.render(); bindForms(); }));

function overview() { return `<div class="stats"><div class="card"><span class="stat-label">TOTAL LEARNERS</span><div class="stat-value">—</div><span class="stat-note">Live Supabase data</span></div><div class="card"><span class="stat-label">PARENT ACCOUNTS</span><div class="stat-value">—</div><span class="stat-note">Access management</span></div><div class="card"><span class="stat-label">ATTENDANCE TODAY</span><div class="stat-value">—</div><span class="stat-note">Daily register</span></div><div class="card"><span class="stat-label">OPEN UPDATES</span><div class="stat-value">—</div><span class="stat-note">Parent notices</span></div></div><div class="panel-grid"><section class="card panel"><h2>School overview</h2><p class="panel-sub">Connect the desktop client to load live academy data.</p><div class="bar-row"><div class="bar-meta"><span>Academic performance</span><strong>—</strong></div><div class="bar-track"><div class="bar-fill" style="width:64%"></div></div></div><div class="bar-row"><div class="bar-meta"><span>Attendance coverage</span><strong>—</strong></div><div class="bar-track"><div class="bar-fill" style="width:82%"></div></div></div><button class="button" data-action="connect">Connect school data</button></section><section class="card panel"><h2>Recent activity</h2><p class="panel-sub">Your latest administrative actions</p><div class="activity"><div class="activity-icon">✓</div><div><strong>Desktop workspace ready</strong><span>Reference-inspired shell created</span></div></div><div class="activity"><div class="activity-icon">↗</div><div><strong>Supabase connection</strong><span>Secure environment handoff pending</span></div></div><div class="activity"><div class="activity-icon">!</div><div><strong>Next action</strong><span>Load learner records</span></div></div></section></div>` }
function tableView(title, sub, headers, rows) { return `<div class="section-title"><div><p class="eyebrow">ADMINISTRATION</p><h2>${title}</h2><p class="panel-sub">${sub}</p></div><button class="button" data-action="new">+ New record</button></div><section class="card"><table class="table"><thead><tr>${headers.map(header => `<th>${header}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map((cell, index) => `<td>${index === row.length - 1 ? `<span class="badge">${cell || 'Ready'}</span>` : cell}</td>`).join('')}</tr>`).join('')}</tbody></table></section>` }
function formView(title, sub, fields) { return `<div class="section-title"><div><p class="eyebrow">MANAGEMENT</p><h2>${title}</h2><p class="panel-sub">${sub}</p></div></div><section class="card"><form class="form-grid" data-form>${fields.map((field, index) => `<div class="field ${index === 1 ? 'full' : ''}"><label>${field}</label>${field === 'Message' || field === 'Body' ? '<textarea></textarea>' : field === 'Status' ? '<select><option>Present</option><option>Absent</option><option>Late</option></select>' : `<input type="text" placeholder="Enter ${field.toLowerCase()}" />`}</div>`).join('')}<div class="field full"><button class="button" type="submit">Save changes</button></div></form></section>` }
function uploadView() { return `<div class="section-title"><div><p class="eyebrow">DOCUMENT INTAKE</p><h2>Class-list Files</h2><p class="panel-sub">Upload PDF, DOCX, or CSV class lists and import learners securely.</p></div><button class="button" data-action="upload">+ Upload file</button></div><section class="card"><div class="empty">Drop a class-list file here or choose Upload file to begin.<br /><small>Imports reconcile existing learners and retain an auditable row count.</small></div></section>` }
function bindForms() { document.querySelectorAll('[data-form]').forEach(form => form.addEventListener('submit', event => { event.preventDefault(); event.target.querySelector('button').textContent = 'Saved locally'; })); document.querySelectorAll('[data-action]').forEach(button => button.addEventListener('click', () => { button.textContent = button.dataset.action === 'connect' ? 'Connection ready' : 'Coming next'; })); }
view.innerHTML = overview(); bindForms();
