-- Nova Crest Academy reference Admin Portal schema
-- Run this script in the Supabase SQL Editor.
-- It is intentionally additive and does not alter or delete existing tables.

create table if not exists public.gallery_media (
  id integer generated by default as identity primary key,
  title varchar(180) not null,
  category varchar(80) not null,
  "imageUrl" text not null,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.site_alert_config (
  id integer generated by default as identity primary key,
  enabled integer not null default 1 check (enabled in (0, 1)),
  message text not null,
  "buttonLabel" varchar(80) not null,
  destination varchar(255) not null,
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.fee_structures (
  id integer generated by default as identity primary key,
  "academicYear" varchar(20) not null unique,
  kindergarten varchar(80) not null,
  "prePrimary" varchar(80) not null,
  "grade1to3" varchar(80) not null,
  "developmentFund" varchar(80) not null,
  "hostelBoarding" varchar(80) not null,
  "registrationFee" varchar(80) not null,
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.school_contact_info (
  id integer generated by default as identity primary key,
  phone varchar(80) not null,
  whatsapp varchar(80) not null,
  email varchar(320) not null,
  location varchar(180) not null,
  "postalBox" varchar(180) not null,
  "registrationNumber" varchar(80) not null,
  "nextTermDate" varchar(80) not null,
  "updatedAt" timestamptz not null default now()
);

-- Optional hardening: enable row-level security. The application server uses
-- the privileged database connection, so these policies do not expose data
-- directly to anonymous browser clients.
alter table public.gallery_media enable row level security;
alter table public.site_alert_config enable row level security;
alter table public.fee_structures enable row level security;
alter table public.school_contact_info enable row level security;
